name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        # pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: "pb-sandbox-1"
    - name: Authenticate gcloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Vertex AI
      env:
        GCP_PROJECT_ID: "pb-sandbox-1"
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        pip install -r requirements.txt
        python kubeflow_train_pipeline.py --ENABLE_CACHING
    - name: Notify Deployment
      run: |
        echo "Deployment successful!"
